format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#E6C384"
truncation_length = 0

[character]
success_symbol = "[❯](#E6C384)"
error_symbol = "[❯](#E82424)"
vimcmd_symbol = "[❮](#E6C384)"

[git_branch]
format = "[$branch]($style)"
style = "#908caa"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#ea9a97) ($ahead_behind$stashed)]($style)"
style = "#98BB6C"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#908caa"

[cmd_duration]
format = " [$duration]($style) "
style = "#E6C384"

[python]
format = "[$virtualenv]($style) "
style = "#98BB6C"
detect_extensions = []
detect_files = []

